version: '3'

services:
  moviepicker-backend:
    container_name: moviepicker-backend
    build: ./backend/
    command: ["/app/entrypoint.sh"]
    volumes:
      - ./backend:/app:z
    ports:
      - "8000:8000"
    depends_on:
      - moviepicker-postgres
    networks:
      - moviepicker-network

  moviepicker-frontend:
    container_name: moviepicker-frontend
    build: ./frontend/
    volumes:
      - ./frontend:/app:z
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - moviepicker-backend
    networks:
      - moviepicker-network

  moviepicker-postgres:
    image: postgres:latest
    container_name: moviepicker-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: moviepickerpass
      POSTGRES_DB: moviepicker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - moviepicker-network

volumes:
  postgres_data:

networks:
  moviepicker-network:
    driver: bridge