# Generated by Django 5.1.5 on 2025-03-30 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('poster_path', models.TextField()),
                ('release_date', models.DateTimeField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('genres', models.ManyToManyField(related_name='movies', to='catalog.genre')),
            ],
            options={
                'db_table': 'catalog_movie',
            },
        ),
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('is_default', models.BooleanField(default=False)),
                ('movies', models.ManyToManyField(related_name='my_lists', to='catalog.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mylist',
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
